name: ci
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      BATON_API_TOKEN: test
      BATON_ORGANIZATION: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-buildkite
        run: go build ./cmd/baton-buildkite
      - name: Run baton-buildkite
        run: ./baton-buildkite
